from pydantic import BaseModel
from datetime import date

class CouponCreate(BaseModel):
    store: str
    code: str = None  # Optional, can be generated by AI
    discount: float
    expires_at: date

class CouponResponse(BaseModel):
    id: int
    store: str
    code: str
    discount: float
    expires_at: date

    class Config:
        orm_mode = True
